# Generated by Django 6.0.1 on 2026-02-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
