# Generated by Django 6.0.3 on 2026-03-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddressmodel',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingaddressmodel',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
