# Generated by Django 5.1.5 on 2026-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetailmodel',
            name='tiktok',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
