# Generated by Django 6.0.3 on 2026-03-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_full_name_shippingaddressmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemmodel',
            name='price',
        ),
    ]
