# Generated by Django 5.1.5 on 2026-03-17 13:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_otherdetailmodel_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetailmodel',
            name='location',
            field=tinymce.models.HTMLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3767838.611094719!2d81.48363299646843!3d28.376722984860947!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3995e8c77d2e68cf%3A0x34a29abcd0cc86de!2sNepal!5e1!3m2!1sen!2snp!4v1773754934762!5m2!1sen!2snp'),
        ),
    ]
