# Generated by Django 6.0.3 on 2026-04-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_orderitemmodel_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='products',
        ),
    ]
