# Generated by Django 6.0.3 on 2026-04-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_orderitemmodel_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api_app.ordermodel'),
        ),
    ]
