# Generated by Django 6.0.3 on 2026-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_cartitemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
