# Generated by Django 6.0.3 on 2026-04-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_paymentmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
