# Generated by Django 6.0.3 on 2026-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_cartitemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetailmodel',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='other_details/'),
        ),
        migrations.AddField(
            model_name='otherdetailmodel',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherdetailmodel',
            name='site_tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
