# Generated by Django 6.0.3 on 2026-03-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_otherdetailmodel_site_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_detail',
            field=models.ManyToManyField(blank=True, to='api_app.orderitemmodel'),
        ),
    ]
