# Generated by Django 6.0.3 on 2026-03-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_ordermodel_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.cartmodel'),
        ),
    ]
