# Generated by Django 6.0.3 on 2026-03-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_ordermodel_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_detail',
        ),
    ]
