# Generated by Django 6.0.3 on 2026-03-30 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_ordermodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.productvariantmodel'),
        ),
    ]
