# Generated by Django 6.0.3 on 2026-03-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_ordermodel_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='varient',
        ),
    ]
